
# Load sample images with known persons' faces and their corresponding names
known_images = [
    ("People'_faces/1.jpg", "The rock"),
    ("People'_faces/2.jpg", "Angelina jolie"),
    ("People'_faces/3.jpeg", "Tom hanks"),
    ("People'_faces/4.jpeg", "Morgan freeman"),
    ("People'_faces/5.jpeg", "Johnny Depp"),
    ("People'_faces/6.jpeg", "Leonardo DiCaprio"),
    ("People'_faces/7.jpeg", "Ryan Reynolds"),
    ("People'_faces/8.jpeg", "Tom Cruise"),
    ("People'_faces/9.jpeg", "Will Smith"),
    ("People'_faces/10.jpeg", "Robert Downey Jr"),
    ("People'_faces/11.jpeg", "Brad Pitt"),
    ("People'_faces/12.jpeg", "Denzel washington"),
    ("People'_faces/13.jpeg", "Al Pacino"),
    ("People'_faces/14.jpg", "Jennifer Aniston"),
    ("People'_faces/15.jpg", "Natalie Portman"),
    ("People'_faces/16.jpg", "jeff bezos"),
    ("People'_faces/17.jpg", "Albert Einstein"),
    ("People'_faces/18.jpeg", "Drew Houston"),
    ("People'_faces/19.jpeg", "Bill Gates"),
    ("People'_faces/20.jpg", "David Beckham"),
    ("People'_faces/21.jpeg", "Evan Spiegel"),
    ("People'_faces/22.jpeg", "George Clooney"),
    ("People'_faces/23.jpg", "J.K. Rowling"),
    ("People'_faces/24.jpg", "Jack Dorsey"),
    ("People'_faces/25.jpeg", "John Hanke"),
    ("People'_faces/26.jpeg", "Ayrton Senna "),
    ("People'_faces/27.jpeg", "Kobe Bryant"),
    ("People'_faces/28.jpeg", "Larry Page"),
    ("People'_faces/29.jpeg", "LeBron James"),
    ("People'_faces/30.jpg", "Malala Yousafzai"),
    ("People'_faces/31.jpeg", "Martin Luther King Jr."),
    ("People'_faces/32.jpeg", "Michael Phelps"),
    ("People'_faces/33.jpeg", "Aly Raisman"),
    ("People'_faces/34.jpeg", "Michelle Obama"),
    ("People'_faces/35.jpeg", "Neil Armstrong"),
    ("People'_faces/36.jpeg", "Oprah Winfrey"),
    ("People'_faces/37.jpg", "Prince Harry"),
    ("People'_faces/38.jpeg", "Tony Hsieh"),
    ("People'_faces/39.jpeg", "Richard Branson "),
    ("People'_faces/40.jpeg", "Roger Federer"),
    ("People'_faces/41.jpeg", "Satya Nadella"),
    ("People'_faces/42.jpeg", "Sergey Brin"),
    ("People'_faces/43.jpeg", "Stewart Butterfield"),
    ("People'_faces/44.jpeg", "Sundar Pichai"),
    ("People'_faces/45.jpeg", "Susan Wojcicki"),
    ("People'_faces/46.jpg", "Tom Hanks"),
    ("People'_faces/47.jpg", "Travis Kalanick"),
    ("People'_faces/48.jpeg", "Amy Adams "),
    ("People'_faces/49.jpg", "Virat Kohli"),
    ("People'_faces/50.jpg", "Warren Buffett"),
    ("People'_faces/51.jpeg", "Aaron Levie"),
    ("People'_faces/52.jpeg", "Michael Schumacher"),
    ("People'_faces/53.jpeg", "Alex Morgan"),
    ("People'_faces/54.jpeg", "Alexis Ohanian"),
    ("People'_faces/55.jpeg", "Anatoly Karpov"),
    ("People'_faces/56.jpeg", "Andrew Garfield "),
    ("People'_faces/57.jpeg", "Arianna Huffington"),
    ("People'_faces/58.jpeg", "Arundhati Roy"),
    ("People'_faces/59.jpeg", "Aung San Suu Kyi"),
    ("People'_faces/60.jpeg", "Ruth Bader Ginsburg"),
    ("People'_faces/61.jpeg", "Steffi Graf "),
    ("People'_faces/62.jpg", "Brendan Eich"),
    ("People'_faces/63.jpeg", "Brian Acton"),
    ("People'_faces/64.jpeg", "Brie Larson"),
    ("People'_faces/65.jpeg", "Charlize Theron"),
    ("People'_faces/66.jpeg", "Craig Newmark"),
    ("People'_faces/67.jpeg", "Cristiano Ronaldo"),
    ("People'_faces/68.jpg", "David Attenborough"),
    ("People'_faces/69.jpeg", "David Filo"),
    ("People'_faces/70.jpeg", "David Karp"),
    ("People'_faces/71.jpeg", "Dennis Ritchie"),
    ("People'_faces/72.jpeg", "Edward Norton"),
    ("People'_faces/73.jpeg", "Emma Watson"),
    ("People'_faces/74.jpeg", "Ethan Hawke"),
    ("People'_faces/75.jpg", "Fabiano Caruana"),
    ("People'_faces/76.jpeg", "Garrett Camp"),
    ("People'_faces/77.jpeg", "Garry Kasparov"),
    ("People'_faces/78.jpeg", "Gary Oldman"),
    ("People'_faces/79.jpeg", "Ginni Rometty"),
    ("People'_faces/80.jpeg", "Guido van Rossum"),
    ("People'_faces/81.jpeg", "Haruki Murakami"),
    ("People'_faces/82.jpeg", "Hayao Miyazaki"),
    ("People'_faces/83.jpeg", "Hillary Clinton"),
    ("People'_faces/84.jpeg", "Steve Carell"),
    ("People'_faces/85.jpeg", "Hiroshi Yamauchi"),
    ("People'_faces/86.jpeg", "Howard Schultz"),
    ("People'_faces/87.jpeg", "Hugh Jackman "),
    ("People'_faces/88.jpeg", "Ian McKellen"),
    ("People'_faces/89.jpeg", "Ilkka Paananen"),
    ("People'_faces/90.jpeg", "Stanley Tucci "),
    ("People'_faces/91.jpg", "Ingvar Kamprad"),
    ("People'_faces/92.jpeg", "Isabel Allende"),
    ("People'_faces/93.jpeg", "Jacinda Ardern"),
    ("People'_faces/94.jpeg", "James Dyson"),
    ("People'_faces/95.jpg", "Jan Koum"),
    ("People'_faces/96.jpeg", "Jane Goodall"),
    ("People'_faces/97.jpeg", "Jimmy Wales"),
    ("People'_faces/98.jpeg", "John Boyne"),
    ("People'_faces/99.jpeg", "John C. Reilly "),
    ("People'_faces/100.jpeg", "jonathan Safran Foer"),
    ("People'_faces/101.jpeg", "Judi Dench"),
    ("People'_faces/102.jpeg", "Julianne Moore "),
    ("People'_faces/103.jpeg", "Katie Ledecky"),
    ("People'_faces/104.jpeg", "Will Wright"),
    ("People'_faces/105.jpeg", "Salman Rushdie"),
    ("People'_faces/106.jpeg", "Khaled Hosseini"),
    ("People'_faces/107.jpeg", "Janus Friis"),
    ("People'_faces/108.jpeg", "Mark Pincus"),
    ("People'_faces/109.jpeg", "Martina Hingis"),
    ("People'_faces/110.jpeg", "Jeff Goldblum"),
    ("People'_faces/111.jpeg", "Max Levchin"),
    ("People'_faces/112.jpeg", "Melinda Gates"),
    ("People'_faces/113.jpeg", "Meryl Streep"),
    ("People'_faces/114.jpeg", "Lionel Messi"),
    ("People'_faces/115.jpeg", "Lois Lowry "),
    ("People'_faces/116.jpeg", "Tony Hsieh"),
    ("People'_faces/117.jpeg", "Magnus Carlsen"),
    ("People'_faces/118.jpeg", "Margaret Atwood"),
    ("People'_faces/119.jpeg", "Marissa Mayer"),
    ("People'_faces/120.jpeg", "Michael Caine"),
    ("People'_faces/121.jpeg", "Michael Pollan"),
    ("People'_faces/122.jpeg", "Naomi Osaka"),
    ("People'_faces/123.jpeg", "Neil Gaiman"),
    ("People'_faces/124.jpeg", "Neymar Jr."),
    ("People'_faces/125.jpeg", "Niklas Zennstrom"),
    ("People'_faces/126.jpeg", "Sheryl Sandberg"),
    ("People'_faces/127.jpeg", "Oscar Isaac "),
    ("People'_faces/128.jpeg", "Palmer Luckey"),
    ("People'_faces/129.jpeg", "Patrick Mahomes"),
    ("People'_faces/130.jpeg", "Patrick Ness"),
    ("People'_faces/131.jpeg", "Paulo Coelho"),
    ("People'_faces/132.jpeg", "Peyton Manning"),
    ("People'_faces/133.jpeg", "Philip Pullman"),
    ("People'_faces/134.jpeg", "Pierre Omidyar"),
    ("People'_faces/135.jpeg", "Reed Hastings"),
    ("People'_faces/136.jpeg", "Linus Torvalds"),
    ("People'_faces/137.jpeg", "Riz Ahmed "),
    ("People'_faces/138.jpeg", "Robert Lewandowski"),
    ("People'_faces/139.jpeg", "Rooney Mara "),
    ("People'_faces/140.jpeg", "Rosalind Picard"),
    ("People'_faces/141.jpeg", "Amy Hennig "),
    ("People'_faces/142.jpeg", "Colin Firth"),
    ("People'_faces/143.jpeg", "Daniel Craig"),
    ("People'_faces/144.jpeg", "Jack Ma"),
    ("People'_faces/145.jpeg", "Jeff Kaplan "),
    ("People'_faces/146.jpeg", "Eddie Redmayne"),
    ("People'_faces/147.jpeg", "Jessica Chastain"),
    ("People'_faces/148.jpeg", "John Romero"),
    ("People'_faces/149.jpeg", "Larry Ellison"),
    ("People'_faces/150.jpeg", "Markus Persson"),
    ("People'_faces/151.jpeg", "Michael Dell"),
    ("People'_faces/152.jpeg", "Novak Djokovic"),
    ("People'_faces/153.jpeg", "Rafael Nadal"),
    ("People'_faces/154.jpeg", "John Krasinski"),
    ("People'_faces/155.jpeg", "Saoirse Ronan"),
    ("People'_faces/156.jpeg", "Matt Damon"),
    ("People'_faces/157.jpeg", "Suzanne Collins"),
    ("People'_faces/158.jpeg", "Terry Pratchett"),
    ("People'_faces/159.jpeg", "Tim Cook"),
    ("People'_faces/160.jpeg", "Tim Schafer"),
    ("People'_faces/161.jpeg", "Tom Brady"),
    ("People'_faces/162.jpeg", "Tony Fadell"),
    ("People'_faces/163.jpeg", "Walt Disney"),
    ("People'_faces/164.jpeg", "Rachel McAdams"),
    ("People'_faces/165.jpeg", "Zinedine Zidane"),
    ("People'_faces/166.jpeg", "Salma Hayek"),
    ("People'_faces/167.jpeg", "Sean Penn"),

    # Add more images and names as needed
]
