# Load sample images with known persons' faces and their corresponding names
known_images = [ 
    ("People'_faces/1.jpg", "Dwayne Johnson"),
    ("People'_faces/2.jpg", "Angelina jolie"),
    ("People'_faces/3.jpeg", "Tom hanks"),
    ("People'_faces/4.jpeg", "Morgan freeman"),
    ("People'_faces/5.jpeg", "Johnny Depp"),
    ("People'_faces/6.jpeg", "Leonardo DiCaprio"),
    ("People'_faces/7.jpeg", "Ryan Reynolds"),
    ("People'_faces/8.jpeg", "Tom Cruise"),
    ("People'_faces/9.jpeg", "Will Smith"),
    ("People'_faces/10.jpeg", "Robert Downey Jr"),
    ("People'_faces/11.jpeg", "Brad Pitt"),
    ("People'_faces/12.jpeg", "Denzel washington"),
    ("People'_faces/13.jpeg", "Al Pacino"),
    ("People'_faces/14.jpg", "Jennifer Aniston"),
    ("People'_faces/15.jpg", "Natalie Portman"),
    ("People'_faces/16.jpg", "jeff bezos"),
    ("People'_faces/17.jpg", "Albert Einstein"),
    ("People'_faces/18.jpeg", "Drew Houston"),
    ("People'_faces/19.jpeg", "Bill Gates"),
    ("People'_faces/20.jpg", "David Beckham"),
    ("People'_faces/21.jpeg", "Evan Spiegel"),
    ("People'_faces/22.jpeg", "George Clooney"),
    ("People'_faces/23.jpg", "J.K. Rowling"),
    ("People'_faces/24.jpg", "Jack Dorsey"),
    ("People'_faces/25.jpeg", "John Hanke"),
    ("People'_faces/26.jpeg", "Ayrton Senna "),
    ("People'_faces/27.jpeg", "Kobe Bryant"),
    ("People'_faces/28.jpeg", "Larry Page"),
    ("People'_faces/29.jpeg", "LeBron James"),
    ("People'_faces/30.jpg", "Malala Yousafzai"),
    ("People'_faces/31.jpeg", "Martin Luther King Jr."),
    ("People'_faces/32.jpeg", "Michael Phelps"),
    ("People'_faces/33.jpeg", "Aly Raisman"),
    ("People'_faces/34.jpeg", "Michelle Obama"),
    ("People'_faces/35.jpeg", "Neil Armstrong"),
    ("People'_faces/36.jpeg", "Oprah Winfrey"),
    ("People'_faces/37.jpg", "Prince Harry"),
    ("People'_faces/38.jpeg", "Tony Hsieh"),
    ("People'_faces/39.jpeg", "Richard Branson "),
    ("People'_faces/40.jpeg", "Roger Federer"),
    ("People'_faces/41.jpeg", "Satya Nadella"),
    ("People'_faces/42.jpeg", "Sergey Brin"),
    ("People'_faces/43.jpeg", "Stewart Butterfield"),
    ("People'_faces/44.jpeg", "Sundar Pichai"),
    ("People'_faces/45.jpeg", "Susan Wojcicki"),
    ("People'_faces/46.jpg", "Tom Hanks"),
    ("People'_faces/47.jpg", "Travis Kalanick"),
    ("People'_faces/48.jpeg", "Amy Adams "),
    ("People'_faces/49.jpg", "Virat Kohli"),
    ("People'_faces/50.jpg", "Warren Buffett"),
    ("People'_faces/51.jpeg", "Aaron Levie"),
    ("People'_faces/52.jpeg", "Michael Schumacher"),
    ("People'_faces/53.jpeg", "Alex Morgan"),
    ("People'_faces/54.jpeg", "Alexis Ohanian"),
    ("People'_faces/55.jpeg", "Anatoly Karpov"),
    ("People'_faces/56.jpeg", "Andrew Garfield "),
    ("People'_faces/57.jpeg", "Arianna Huffington"),
    ("People'_faces/58.jpeg", "Arundhati Roy"),
    ("People'_faces/59.jpeg", "Aung San Suu Kyi"),
    ("People'_faces/60.jpeg", "Ruth Bader Ginsburg"),
    ("People'_faces/61.jpeg", "Steffi Graf "),
    ("People'_faces/62.jpg", "Brendan Eich"),
    ("People'_faces/63.jpeg", "Brian Acton"),
    ("People'_faces/64.jpeg", "Brie Larson"),
    ("People'_faces/65.jpeg", "Charlize Theron"),
    ("People'_faces/66.jpeg", "Craig Newmark"),
    ("People'_faces/67.jpeg", "Cristiano Ronaldo"),
    ("People'_faces/68.jpg", "David Attenborough"),
    ("People'_faces/69.jpeg", "David Filo"),
    ("People'_faces/70.jpeg", "David Karp"),
    ("People'_faces/71.jpeg", "Dennis Ritchie"),
    ("People'_faces/72.jpeg", "Edward Norton"),
    ("People'_faces/73.jpeg", "Emma Watson"),
    ("People'_faces/74.jpeg", "Ethan Hawke"),
    ("People'_faces/75.jpg", "Fabiano Caruana"),
    ("People'_faces/76.jpeg", "Garrett Camp"),
    ("People'_faces/77.jpeg", "Garry Kasparov"),
    ("People'_faces/78.jpeg", "Gary Oldman"),
    ("People'_faces/79.jpeg", "Ginni Rometty"),
    ("People'_faces/80.jpeg", "Guido van Rossum"),
    ("People'_faces/81.jpeg", "Haruki Murakami"),
    ("People'_faces/82.jpeg", "Hayao Miyazaki"),
    ("People'_faces/83.jpeg", "Hillary Clinton"),
    ("People'_faces/84.jpeg", "Steve Carell"),
    ("People'_faces/85.jpeg", "Hiroshi Yamauchi"),
    ("People'_faces/86.jpeg", "Howard Schultz"),
    ("People'_faces/87.jpeg", "Hugh Jackman "),
    ("People'_faces/88.jpeg", "Ian McKellen"),
    ("People'_faces/89.jpeg", "Ilkka Paananen"),
    ("People'_faces/90.jpeg", "Stanley Tucci "),
    ("People'_faces/91.jpg", "Ingvar Kamprad"),
    ("People'_faces/92.jpeg", "Isabel Allende"),
    ("People'_faces/93.jpeg", "Jacinda Ardern"),
    ("People'_faces/94.jpeg", "James Dyson"),
    ("People'_faces/95.jpg", "Jan Koum"),
    ("People'_faces/96.jpeg", "Jane Goodall"),
    ("People'_faces/97.jpeg", "Jimmy Wales"),
    ("People'_faces/98.jpeg", "John Boyne"),
    ("People'_faces/99.jpeg", "John C. Reilly "),
    ("People'_faces/100.jpeg", "jonathan Safran Foer"),
    ("People'_faces/101.jpeg", "Judi Dench"),
    ("People'_faces/102.jpeg", "Julianne Moore "),
    ("People'_faces/103.jpeg", "Katie Ledecky"),
    ("People'_faces/104.jpeg", "Will Wright"),
    ("People'_faces/105.jpeg", "Salman Rushdie"),
    ("People'_faces/106.jpeg", "Khaled Hosseini"),
    ("People'_faces/107.jpeg", "Janus Friis"),
    ("People'_faces/108.jpeg", "Mark Pincus"),
    ("People'_faces/109.jpeg", "Martina Hingis"),
    ("People'_faces/110.jpeg", "Jeff Goldblum"),
    ("People'_faces/111.jpeg", "Max Levchin"),
    ("People'_faces/112.jpeg", "Melinda Gates"),
    ("People'_faces/113.jpeg", "Meryl Streep"),
    ("People'_faces/114.jpeg", "Lionel Messi"),
    ("People'_faces/115.jpeg", "Lois Lowry "),
    ("People'_faces/116.jpeg", "Tony Hsieh"),
    ("People'_faces/117.jpeg", "Magnus Carlsen"),
    ("People'_faces/118.jpeg", "Margaret Atwood"),
    ("People'_faces/119.jpeg", "Marissa Mayer"),
    ("People'_faces/120.jpeg", "Michael Caine"),
    ("People'_faces/121.jpeg", "Michael Pollan"),
    ("People'_faces/122.jpeg", "Naomi Osaka"),
    ("People'_faces/123.jpeg", "Neil Gaiman"),
    ("People'_faces/124.jpeg", "Neymar Jr."),
    ("People'_faces/125.jpeg", "Niklas Zennstrom"),
    ("People'_faces/126.jpeg", "Sheryl Sandberg"),
    ("People'_faces/127.jpeg", "Oscar Isaac "),
    ("People'_faces/128.jpeg", "Palmer Luckey"),
    ("People'_faces/129.jpeg", "Patrick Mahomes"),
    ("People'_faces/130.jpeg", "Patrick Ness"),
    ("People'_faces/131.jpeg", "Paulo Coelho"),
    ("People'_faces/132.jpeg", "Peyton Manning"),
    ("People'_faces/133.jpeg", "Philip Pullman"),
    ("People'_faces/134.jpeg", "Pierre Omidyar"),
    ("People'_faces/135.jpeg", "Reed Hastings"),
    ("People'_faces/136.jpeg", "Linus Torvalds"),
    ("People'_faces/137.jpeg", "Riz Ahmed "),
    ("People'_faces/138.jpeg", "Robert Lewandowski"),
    ("People'_faces/139.jpeg", "Rooney Mara "),
    ("People'_faces/140.jpeg", "Rosalind Picard"),
    ("People'_faces/141.jpeg", "Amy Hennig "),
    ("People'_faces/142.jpeg", "Colin Firth"),
    ("People'_faces/143.jpeg", "Daniel Craig"),
    ("People'_faces/144.jpeg", "Jack Ma"),
    ("People'_faces/145.jpeg", "Jeff Kaplan "),
    ("People'_faces/146.jpeg", "Eddie Redmayne"),
    ("People'_faces/147.jpeg", "Jessica Chastain"),
    ("People'_faces/148.jpeg", "John Romero"),
    ("People'_faces/149.jpeg", "Larry Ellison"),
    ("People'_faces/150.jpeg", "Markus Persson"),
    ("People'_faces/151.jpeg", "Michael Dell"),
    ("People'_faces/152.jpeg", "Novak Djokovic"),
    ("People'_faces/153.jpeg", "Rafael Nadal"),
    ("People'_faces/154.jpeg", "John Krasinski"),
    ("People'_faces/155.jpeg", "Saoirse Ronan"),
    ("People'_faces/156.jpeg", "Matt Damon"),
    ("People'_faces/157.jpeg", "Suzanne Collins"),
    ("People'_faces/158.jpeg", "Terry Pratchett"),
    ("People'_faces/159.jpeg", "Tim Cook"),
    ("People'_faces/160.jpeg", "Tim Schafer"),
    ("People'_faces/161.jpeg", "Tom Brady"),
    ("People'_faces/162.jpeg", "Tony Fadell"),
    ("People'_faces/163.jpeg", "Walt Disney"),
    ("People'_faces/164.jpeg", "Rachel McAdams"),
    ("People'_faces/165.jpeg", "Zinedine Zidane"),
    ("People'_faces/166.jpeg", "Salma Hayek"),
    ("People'_faces/167.jpeg", "Sean Penn"),
    ("People'_faces/168.jpg", "Andy Garcia "),
    ("People'_faces/169.jpg", "Bob Iger"),
    ("People'_faces/170.jpg", "Chris Evans"),
    ("People'_faces/171.jpg", "Chris Hemsworth"),
    ("People'_faces/172.jpg", "Felipe Massa"),
    ("People'_faces/173.jpeg", "Elon musk"),
    ("People'_faces/174.jpg", "Henry Cavill"),
    ("People'_faces/175.jpg", "Idris Elba"), 
    ("People'_faces/176.jpg", " Christian Horner"),
    ("People'_faces/177.jpg", " Jimmy Wales "),
    ("People'_faces/178.jpg", "Jim Carre"),
    ("People'_faces/179.jpg", "Matthew McConaughey"),
    ("People'_faces/180.jpg", "Mark Zuckerberg "),
    ("People'_faces/181.jpeg", "Nasser Al-Khelaifi"),
    ("People'_faces/182.jpeg", "Robert De Niro"),
    ("People'_faces/183.jpg", "Russell Crowe"), 
    ("People'_faces/184.jpg", "Ryan Gosling"),
    ("People'_faces/185.jpeg", "Steven Paul Jobs"),
    ("People'_faces/186.jpeg", "Theo James"),
    ("People'_faces/187.jpeg", "Tony Goldwyn"), 
    ("People'_faces/188.jpg", "Buzz Aldrin"),
    ("People'_faces/189.jpeg", "Karim Benzema"),
    ("People'_faces/190.jpeg", "Macaulay Culkin"),
    ("People'_faces/191.jpg", "Yasser AlShahrani"),
    ("People'_faces/192.jpeg", "Daniel Radcliffe"),
    ("People'_faces/193.jpg", "Jim Broadbent"),
    ("People'_faces/194.jpg", "Alan Rickman"),
    ("People'_faces/195.jpeg", "John Heard"),
    ("People'_faces/196.jpeg", "Jason Statham"),
    ("People'_faces/197.jpg", "Kareem Abdul Jabbar"),
    ("People'_faces/198.jpg", "Stephen Curry"),
    ("People'_faces/199.jpg", "Ma Huateng"),
    ("People'_faces/200.jpeg", "Steve Ballmer"),
    ("People'_faces/201.jpg", "Robson Walton"),
    ("People'_faces/202.jpeg", "Amanicio Ortega"),
    ("People'_faces/203.jpeg", "Mukesh Ambani"),
    ("People'_faces/204.jpg", "David Koch"),
    ("People'_faces/205.jpeg", "Bernard Arnault"),
    ("People'_faces/206.jpeg", "Casey Affleck"),
    ("People'_faces/207.jpeg", "Benicio del Toro"),
    ("People'_faces/208.jpeg", "Tim Robbins"),
    ("People'_faces/209.jpeg", "Chris Hadfield"),
    ("People'_faces/210.jpeg", "Javier Bardem"),
    ("People'_faces/211.jpeg", "Heath Ledger"),
    ("People'_faces/212.jpeg", "Christoph Waltz"),
    ("People'_faces/213.jpg", "Jared Leto"),
    ("People'_faces/214.jpeg", "Keston Bledman"),
    ("People'_faces/215.jpg", "Mohamed Salah"),
    ("People'_faces/216.jpg", "Jorginho"),
    ("People'_faces/217.jpeg", "Erling Haaland"),
    ("People'_faces/218.jpeg", "Gianluigi Donnarumma"),
    ("People'_faces/219.jpeg", "Joshua Kimmich"),
    ("People'_faces/220.jpeg", "Giorgio Chiellini"),
    ("People'_faces/221.jpeg", "Phil Foden"),
    ("People'_faces/222.jpeg", "Thomas Muller"),
    ("People'_faces/223.jpeg", "Jan Oblak"),
    ("People'_faces/224.jpeg", "Trent Alexander Arnold"),
    ("People'_faces/225.jpeg", "Manuel Neuer"),
    ("People'_faces/226.jpg", "Marco Verratti"),
    ("People'_faces/227.jpg", "Achraf Hakimi"),
    ("People'_faces/228.jpeg", "Luka Modric"),
    ("People'_faces/229.jpeg", "Marquinhos"),
    ("People'_faces/230.jpg", "Bernardo Silva"),
    ("People'_faces/231.jpeg", "Yunis Abdelhamid"),
    ("People'_faces/232.jpeg", "Antonio Banderas"),
    ("People'_faces/233.jpeg", "Dougray Scott"),
    ("People'_faces/234.jpeg", "Rodrigo Santoro"),
    ("People'_faces/235.jpeg", "Joaquim de Almeida"),
    ("People'_faces/236.jpeg", "Adrien Brody"),
    ("People'_faces/237.jpeg", "Jean Reno"),
    ("People'_faces/238.jpg", "Kal Penn"),
    ("People'_faces/239.jpeg", "Omar Sharif"),
    ("People'_faces/240.jpg", "John Leguizamo"),
    ("People'_faces/241.jpeg", "Amitabh Bachchan"),
    ("People'_faces/242.jpeg", "James Cameron"),
    ("People'_faces/243.jpeg", "Rowan Atkinson"),
    ("People'_faces/244.jpg", "Ahmed Ali"),
    ("People'_faces/245.jpg", "Hussein Mohamed"),
    ("People'_faces/246.jpg", "Ismail Omar"),
    ("People'_faces/247.jpg", "Hamad Abdullah"),
    ("People'_faces/248.jpg", "Hani Khaled"),
    ("People'_faces/249.jpg", "Abdul Malik Jaber"),
    ("People'_faces/250.jpg", "Ryan Jassim"),
    ("People'_faces/251.jpg", "Muhammad Thamer"),
    ("People'_faces/252.jpg", "Jack Peter"),
    ("People'_faces/253.jpg", "Ali Nasser"),
    ("People'_faces/254.jpg", "Charlie"),
    ("People'_faces/255.jpg", "Tyrrell Hatton"),
    ("People'_faces/256.jpeg", "David Yates"),
    ("People'_faces/257.jpg", "Georgie Jesus"),
    ("People'_faces/258.jpeg", "Sam Cristoforetti"),
    ("People'_faces/259.jpeg", "John Carmack"), 
    ("People'_faces/260.jpeg", "Todd Howard"),
    ("People'_faces/261.jpg", "Mark Cerny"),
    ("People'_faces/262.jpeg", "Ed Boon"),
    ("People'_faces/263.jpg", "Jim Ryan"),
    ("People'_faces/264.jpg", "Angela Merkel"),
    ("People'_faces/265.jpg", "Elizabeth Holmes"),
    ("People'_faces/266.jpg", "Neil deGrasse Tyson"),
    ("People'_faces/267.jpg", "Malcolm Gladwell"),
    ("People'_faces/268.jpeg", "Michael Bloomberg"),
    ("People'_faces/269.jpeg", "Sara Blakely"),
    ("People'_faces/270.jpg", "Bertrand Piccard"),
    ("People'_faces/271.jpeg", "Ryan Murphy"),
    ("People'_faces/272.jpeg", "Karl Lagerfeld"),
    ("People'_faces/273.jpg", "Giorgio Armani"),
    ("People'_faces/274.jpg", "Christian Louboutin"),
    ("People'_faces/275.jpeg", "Tom Ford"),
    ("People'_faces/276.jpg", "Paula Scher"),
    ("People'_faces/277.jpg", "Kylian Mbappe"),
    ("People'_faces/278.jpg", "Dara Khosrowshahi"),
    ("People'_faces/279.jpeg", "Chad Hurley"), 
    ("People'_faces/280.jpg", "Lewis Hamilton"),
    ("People'_faces/281.jpeg", "Sebastian Vettel"),
    ("People'_faces/282.jpg", "Valentino Rossi"),
    ("People'_faces/283.jpg", "Daniel Ricciardo"),
    ("People'_faces/284.jpg", "Fernando Alonso"),
    ("People'_faces/285.jpg", "Alain Prost"),
    ("People'_faces/286.jpg", "Carlos Sainz Jr"),
    ("People'_faces/287.jpeg", "Mario Andretti"),
    ("People'_faces/288.jpeg", "Max Verstappen"),
    ("People'_faces/289.jpeg", "Kimi Raikkonen"),
    ("People'_faces/290.jpeg", "Charles Leclerc"),
    ("People'_faces/291.jpeg", "Jamie Chadwick"),
    ("People'_faces/292.jpg", "Tobias Moers"),
    ("People'_faces/293.jpeg", "Andreas Seidl"),
    ("People'_faces/294.jpg", "Bob Beckel"),
    ("People'_faces/295.jpeg", "Jennie Gow"),
    ("People'_faces/296.jpeg", "Roberto Ravaglia"),
    ("People'_faces/297.jpg", "Diana Carter"),
    ("People'_faces/298.jpg", "Susie Wolff"),
    ("People'_faces/299.jpg", "Nancy Roman"), 
    ("People'_faces/300.jpeg", "David Dewhurst"),
]
